{
 "title": "Admin Dashboard",
 "time": { "from": "now-24h", "to": "now-15s" },
 "templating": {
  "list": [
   { "name": "field", "query": "views, likes, comments" },
   { "name": "sponsored_only", "label": "Sponsored Only", "query": "true, false" }
  ]
 },
 "panels": [
  {
   "title": "Total ${field}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"views\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"views\")\n  |> filter(fn: (r) => r[\"_field\"] == \"${field}\")\n  |> filter(fn: (r) => (${sponsored_only} == false) or r[\"sponsor_id\"] != \"-1\")\n  |> aggregateWindow(every: $__interval, fn: max, createEmpty: true)\n  // |> group(columns: [\"url\"])\n  // |> aggregateWindow(every: $__interval, fn: max, createEmpty: true)\n  |> fill(usePrevious: true)\n  |> group()\n  |> aggregateWindow(every: 30m, fn: sum, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Breakdown by account",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\n\nfrom(bucket: \"views\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"views\")\n  |> filter(fn: (r) => r[\"_field\"] == \"${field}\")\n  |>drop(columns: [\"strategy_id\"])\n  |>group(columns: [\"url\"])\n    |> last()\n    //|> map(fn: (r) => ({ r with pretty_account: r.platform+\"/\"+r.username}))\n    |>group(columns: [\"username\"])\n   |> sum()\n    |> keep(columns: [\"_value\",\"_field\",\"username\"])\n    |> rename(columns: {_value: \"\"})\n    \n\n\n"
    }
   ]
  },
  {
   "title": "Breakdown by platform",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\n\nfrom(bucket: \"views\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"views\")\n  |> filter(fn: (r) => r[\"_field\"] == \"${field}\")\n//  |> filter(fn: (r) => r[\"url\"] == \"${url}\")\n  |>drop(columns: [\"strategy_id\"])\n  |>group(columns: [\"url\"])\n// |> sum()\n    |>group(columns: [\"platform\"])\n    |>last()\n\n\n"
    }
   ]
  },
  {
   "title": "Views per hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"experimental/aggregate\"\n\n\n\nimport \"date\"\n\nfrom(bucket: \"views\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"views\")\n  |> filter(fn: (r) => r[\"_field\"] == \"${field}\")\n  |> aggregateWindow(every: $__interval, fn: max, createEmpty: true)\n  |> fill(usePrevious: true)\n  |> group()\n  |> aggregateWindow(every: 30m, fn: sum, createEmpty: false)\n        |> derivative(unit: 1h, nonNegative: true)\n\n\n\n"
    }
   ]
  },
  {
   "title": "Breakdown by account",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "query": "from(bucket: \"views\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"views\")\n  |> filter(fn: (r) => r[\"_field\"] == \"${field}\")\n  |> group(columns: [\"username\"])\n  |> aggregateWindow(every: 30m, fn: sum, createEmpty: false)\n  //|> group()\n  |> aggregateWindow(every: $__interval, fn: max, createEmpty: true)\n\n\n\n"
    }
   ]
  }
 ]
}