{
 "title": "Filter by video URL",
 "description": "paste a video link and see its views only",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "url" }
  ]
 },
 "panels": [
  {
   "title": "Video Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select url as \"Link\", posted_date as \"Posted\", title as \"Caption\", writer.name as \"Writer Name\", cowriter.name as \"Co-Writer Name\", src.name as \"Source\", v.name as \"Voice\" from video \njoin writer on writer.id = video.writer_id\n left join writer cowriter on cowriter.id = video.co_writer_id\n left join source src on src.id = video.source_id \n left join voice v on v.id = video.voice_id  where url = '${url}';"
    }
   ]
  },
  {
   "title": "Strategies",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT s.name, s.id from video_strategies join video v on video_id = v.id join strategy s on strategy_id = s.id where url = '${url}'"
    }
   ]
  },
  {
   "title": "Retention Graph",
   "type": "trend",
   "description": "Hover over a data point to see the timestamp",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n    instant_s, value AS \"Percent of Viewers\"\nFROM\n    retention_rate\n        join video on retention_rate.video_id = video.id\nwhere\n        video.url = '$url'\n\n        order by instant_s"
    }
   ]
  },
  {
   "title": "All-time views",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"views\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"views\")\n  |> filter(fn: (r) => r[\"_field\"] == \"views\")\n |> filter(fn: (r) => r[\"url\"] == \"${url}\")\n|>drop(columns: [\"strategy_id\"])\n  |>group(columns: [\"url\"])\n  |> aggregateWindow(every: 20m, fn: max, createEmpty: false)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Views over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"views\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"views\")\n  |> filter(fn: (r) => r[\"_field\"] == \"views\")\n |> filter(fn: (r) => r[\"url\"] == \"${url}\")\n//|>drop(columns: [\"strategy_id\"])\n |>group(columns: [\"url\"])\n   |> aggregateWindow(every: $__interval, fn: max, createEmpty: false)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    }
   ]
  }
 ]
}