{
 "title": "Finances",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "writer",
    "label": "Writer",
    "query": "SELECT id AS __value, name AS __text FROM writer"
   },
   {
    "name": "sponsor",
    "label": "Sponsor",
    "query": "SELECT id AS __value, name AS __text FROM sponsor"
   },
   { "name": "platform", "label": "Platform", "query": "SELECT platform FROM account" },
   { "name": "account", "label": "Account", "query": "SELECT username FROM account" }
  ]
 },
 "panels": [
  {
   "title": "Revenue total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "\n\nfrom(bucket: \"views\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"views\")\n  |> filter(fn: (r) => r[\"_field\"] == \"revenue\")\n    |> filter(fn: (r) => contains(set: ${writer:json},value: r[\"writer_id\"]))\n    |> filter(fn: (r) => contains(set: ${sponsor:json},value: r[\"sponsor_id\"]))\n\n    |> filter(fn: (r) => contains(set: ${platform:json},value: r[\"platform\"]))\n    |> filter(fn: (r) => contains(set: ${account:json},value: r[\"username\"]))\n//  |> filter(fn: (r) => r[\"url\"] == \"${url}\")\n  |>drop(columns: [\"strategy_id\"])\n  |>group(columns: [\"url\"])\n// |> sum()\n  |> aggregateWindow(every: 50m, fn: max, createEmpty: false)\n   |> group()\n  |> aggregateWindow(every: 50m, fn: sum, createEmpty: false)\n\n"
    }
   ]
  },
  {
   "title": "Account payments total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "\n\nfrom(bucket: \"views\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"views\")\n  |> filter(fn: (r) => r[\"_field\"] == \"account_pay\")\n    |> filter(fn: (r) => contains(set: ${writer:json},value: r[\"writer_id\"]))\n    |> filter(fn: (r) => contains(set: ${sponsor:json},value: r[\"sponsor_id\"]))\n\n    |> filter(fn: (r) => contains(set: ${platform:json},value: r[\"platform\"]))\n    |> filter(fn: (r) => contains(set: ${account:json},value: r[\"username\"]))\n//  |> filter(fn: (r) => r[\"url\"] == \"${url}\")\n  |>drop(columns: [\"strategy_id\"])\n  |>group(columns: [\"url\"])\n// |> sum()\n  |> aggregateWindow(every: 50m, fn: max, createEmpty: false)\n   |> group()\n  |> aggregateWindow(every: 50m, fn: sum, createEmpty: false)\n\n"
    }
   ]
  },
  {
   "title": "Writer payments total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\n\nfrom(bucket: \"views\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"views\")\n  |> filter(fn: (r) => r[\"_field\"] == \"writer_pay\")\n    |> filter(fn: (r) => contains(set: ${writer:json},value: r[\"writer_id\"]))\n    |> filter(fn: (r) => contains(set: ${sponsor:json},value: r[\"sponsor_id\"]))\n\n    |> filter(fn: (r) => contains(set: ${platform:json},value: r[\"platform\"]))\n    |> filter(fn: (r) => contains(set: ${account:json},value: r[\"username\"]))\n//  |> filter(fn: (r) => r[\"url\"] == \"${url}\")\n  |>drop(columns: [\"strategy_id\"])\n  |>group(columns: [\"url\"])\n// |> sum()\n  |> aggregateWindow(every: 50m, fn: max, createEmpty: false)\n   |> group()\n  |> aggregateWindow(every: 50m, fn: sum, createEmpty: false)\n\n"
    }
   ]
  },
  {
   "title": "Revenue total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "\n\nfrom(bucket: \"views\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"views\")\n  |> filter(fn: (r) => r[\"_field\"] == \"revenue\")\n    |> filter(fn: (r) => contains(set: ${writer:json},value: r[\"writer_id\"]))\n    |> filter(fn: (r) => contains(set: ${sponsor:json},value: r[\"sponsor_id\"]))\n\n    |> filter(fn: (r) => contains(set: ${platform:json},value: r[\"platform\"]))\n    |> filter(fn: (r) => contains(set: ${account:json},value: r[\"username\"]))\n//  |> filter(fn: (r) => r[\"url\"] == \"${url}\")\n  |>drop(columns: [\"strategy_id\"])\n  |>group(columns: [\"url\"])\n// |> sum()\n  |> aggregateWindow(every: 50m, fn: max, createEmpty: false)\n   |> group()\n  |> aggregateWindow(every: 50m, fn: sum, createEmpty: false)\n\n"
    }
   ]
  },
  {
   "title": "Account payments total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "\n\nfrom(bucket: \"views\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"views\")\n  |> filter(fn: (r) => r[\"_field\"] == \"account_pay\")\n    |> filter(fn: (r) => contains(set: ${writer:json},value: r[\"writer_id\"]))\n    |> filter(fn: (r) => contains(set: ${sponsor:json},value: r[\"sponsor_id\"]))\n\n    |> filter(fn: (r) => contains(set: ${platform:json},value: r[\"platform\"]))\n    |> filter(fn: (r) => contains(set: ${account:json},value: r[\"username\"]))\n//  |> filter(fn: (r) => r[\"url\"] == \"${url}\")\n  |>drop(columns: [\"strategy_id\"])\n  |>group(columns: [\"url\"])\n// |> sum()\n  |> aggregateWindow(every: 50m, fn: max, createEmpty: false)\n   |> group()\n  |> aggregateWindow(every: 50m, fn: sum, createEmpty: false)\n\n"
    }
   ]
  },
  {
   "title": "Writer payments total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "\n\nfrom(bucket: \"views\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"views\")\n  |> filter(fn: (r) => r[\"_field\"] == \"writer_pay\")\n    |> filter(fn: (r) => contains(set: ${writer:json},value: r[\"writer_id\"]))\n    |> filter(fn: (r) => contains(set: ${sponsor:json},value: r[\"sponsor_id\"]))\n\n    |> filter(fn: (r) => contains(set: ${platform:json},value: r[\"platform\"]))\n    |> filter(fn: (r) => contains(set: ${account:json},value: r[\"username\"]))\n//  |> filter(fn: (r) => r[\"url\"] == \"${url}\")\n  |>drop(columns: [\"strategy_id\"])\n  |>group(columns: [\"url\"])\n// |> sum()\n  |> aggregateWindow(every: 50m, fn: max, createEmpty: false)\n   |> group()\n  |> aggregateWindow(every: 50m, fn: sum, createEmpty: false)\n\n"
    }
   ]
  },
  {
   "title": "Sponsor Revenue Breakdown",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "// import \"experimental/aggregate\"\n\nfrom(bucket: \"views\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"views\")\n  |> filter(fn: (r) => r[\"_field\"] == \"revenue\")\n  |> filter(fn: (r) => contains(set: ${writer:json},value: r[\"writer_id\"]))\n    |> filter(fn: (r) => contains(set: ${sponsor:json},value: r[\"sponsor_id\"]))\n    |> filter(fn: (r) => contains(set: ${platform:json},value: r[\"platform\"]))\n    |> filter(fn: (r) => contains(set: ${account:json},value: r[\"username\"]))\n |> group(columns: [\"url\"])\n |> last()\n |> group(columns: [\"sponsor_id\"])\n\n    |> sum()\n   |> group()\n  |> rename(columns: {_value: \"Amount\"})"
    }
   ]
  },
  {
   "title": "Account cost breakdown",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "// import \"experimental/aggregate\"\n\nfrom(bucket: \"views\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"views\")\n  |> filter(fn: (r) => r[\"_field\"] == \"account_pay\")\n  |> filter(fn: (r) => contains(set: ${writer:json},value: r[\"writer_id\"]))\n    |> filter(fn: (r) => contains(set: ${sponsor:json},value: r[\"sponsor_id\"]))\n\n    |> filter(fn: (r) => contains(set: ${platform:json},value: r[\"platform\"]))\n    |> filter(fn: (r) => contains(set: ${account:json},value: r[\"username\"]))\n  // |> derivative(unit: 1m, nonNegative: true)\n |> group(columns: [\"url\"])\n|> last()\n |> group(columns: [\"username\"])\n\n  //  |> aggregateWindow(every: 20m, fn: mean, createEmpty: false)\n    |> sum()\n   |> group()\n   //|> keep(columns: [\"username\", \"_value\"])\n  |> rename(columns: {_value: \"Amount\"})"
    }
   ]
  },
  {
   "title": "Writer cost breakdown",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "// import \"experimental/aggregate\"\n\nfrom(bucket: \"views\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"views\")\n  |> filter(fn: (r) => r[\"_field\"] == \"writer_pay\")\n  |> filter(fn: (r) => contains(set: ${writer:json},value: r[\"writer_id\"]))\n    |> filter(fn: (r) => contains(set: ${sponsor:json},value: r[\"sponsor_id\"]))\n    |> filter(fn: (r) => contains(set: ${platform:json},value: r[\"platform\"]))\n    |> filter(fn: (r) => contains(set: ${account:json},value: r[\"username\"]))\n |> group(columns: [\"url\"])\n |> last()\n |> group(columns: [\"writer_id\"])\n\n    |> sum()\n   |> group()\n  |> rename(columns: {_value: \"Amount\"})"
    }
   ]
  },
  {
   "title": "Received Sponsor Payments",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT date, sponsor.name as \"Sponsor Name\",  amount, details from sponsor_payment join sponsor on sponsor_payment.sponsor_id = sponsor.id"
    }
   ]
  }
 ]
}