{
 "title": "Retention",
 "time": { "from": "now/y", "to": "now/y" },
 "templating": {
  "list": [
   { "name": "seconds", "label": "At # of seconds", "query": "5" },
   { "name": "min_retention", "label": "Retention above %", "query": "0" }
  ]
 },
 "panels": [
  {
   "title": "Instructions",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Enter your desired % retention at # of seconds in the fields above <br/> \n<b> Only videos posted within the selected time range will be shown </b>\nEdit the time range at the top right corner"
   }
  },
  {
   "title": "Matching Videos",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT v.url as \"Details\", v.duration as \"Video length\", value as \"Retention at ${seconds}s\" from retention_rate join video v on v.id = video_id where instant_s = $seconds and value > $min_retention and $__timeFilter(v.posted_date) "
    }
   ]
  },
  {
   "title": "Percent of videos meeting 50% at 5s",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(video_id) from retention_rate join video v on v.id = video_id  where instant_s = 3 and value > 70 and $__timeFilter(v.posted_date) "
    },
    {
     "rawSql": "SELECT COUNT(v.id) FROM retention_rate join video v on v.id = video_id where $__timeFilter(v.posted_date) and instant_s = 5"
    },
    { "expression": "100 * $A / $B", "type": "math" }
   ]
  },
  {
   "title": "60% at 5s OR 70% at 3s",
   "type": "gauge",
   "description": "Percent of all videos",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) from\n    (select 1 from retention_rate join video v on v.id = video_id\n        where ((instant_s = 3 and value > 70) or (instant_s = 5 and value > 60)) and $__timeFilter(v.posted_date) \n GROUP BY video_id\n HAVING COUNT(value) = 2\n        ) AS t ;\n \n"
    },
    {
     "rawSql": "SELECT COUNT(v.id) FROM retention_rate join video v on v.id = video_id where $__timeFilter(v.posted_date) and instant_s = 5"
    },
    { "expression": "100 * $A / $B", "type": "math" }
   ]
  },
  {
   "title": "60% at 5s AND 70% at 3s",
   "type": "gauge",
   "description": "Percent of all videos",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) from\n    (select 1 from retention_rate join video v on v.id = video_id\n        where ((instant_s = 3 and value > 70) and (instant_s = 5 and value > 60)) and $__timeFilter(v.posted_date) \n GROUP BY video_id\n HAVING COUNT(value) = 2\n        ) AS t ;\n \n"
    },
    {
     "rawSql": "SELECT COUNT(v.id) FROM retention_rate join video v on v.id = video_id where $__timeFilter(v.posted_date) and instant_s = 5"
    },
    { "expression": "100 * $A / $B", "type": "math" }
   ]
  }
 ]
}