{
 "title": "Sponsor Video Details",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "video_url", "label": "Video URL" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# [Click to view video on TikTok](${video_url})"
   }
  },
  {
   "title": "Views",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "query": "from(bucket: \"views\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"views\")\n  |> filter(fn: (r) => r[\"_field\"] == \"views\")\n  |> filter(fn: (r) => r[\"url\"] == \"${video_url}\")\n  |>drop(columns: [\"strategy_id\"])\n  |>group(columns: [\"url\"])\n// |> sum()\n  |> aggregateWindow(every: 30m, fn: max, createEmpty: true)"
    }
   ]
  },
  {
   "title": "Hourly Views",
   "type": "barchart",
   "description": "Each bar is the difference previous hour to listed hour ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"views\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"views\")\n  |> filter(fn: (r) => r[\"_field\"] == \"views\")\n  |> filter(fn: (r) => r[\"url\"] == \"${video_url}\")\n  |>drop(columns: [\"strategy_id\"])\n  |>group(columns: [\"url\"])\n// |> sum()\n  |> aggregateWindow(every: 1h, fn: max, createEmpty: true)\n  |> derivative(unit: 1h)  \n |> group()\n    |> keep(columns: [\"_time\", \"_value\"])\n"
    }
   ]
  },
  { "title": "Likes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Likes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"views\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"views\")\n  |> filter(fn: (r) => r[\"_field\"] == \"likes\")\n  |> filter(fn: (r) => r[\"url\"] == \"${video_url}\")\n  |>drop(columns: [\"strategy_id\"])\n  |>group(columns: [\"url\"])\n// |> sum()\n  |> aggregateWindow(every: 30m, fn: max, createEmpty: true)"
    }
   ]
  },
  {
   "title": "Hourly Likes",
   "type": "barchart",
   "description": "Each bar is the difference previous hour to listed hour ",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"views\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"views\")\n  |> filter(fn: (r) => r[\"_field\"] == \"likes\")\n  |> filter(fn: (r) => r[\"url\"] == \"${video_url}\")\n  |>drop(columns: [\"strategy_id\"])\n  |>group(columns: [\"url\"])\n// |> sum()\n  |> aggregateWindow(every: 30m, fn: max, createEmpty: true)\n  |> derivative(unit: 1h)  \n |> group()\n    |> keep(columns: [\"_time\", \"_value\"])\n"
    }
   ]
  },
  {
   "title": "Hourly Likes",
   "type": "timeseries",
   "description": "Each bar is the difference previous hour to listed hour ",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "query": "from(bucket: \"views\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"views\")\n  |> filter(fn: (r) => r[\"_field\"] == \"likes\")\n  |> filter(fn: (r) => r[\"url\"] == \"${video_url}\")\n  |>drop(columns: [\"strategy_id\"])\n  |>group(columns: [\"url\"])\n// |> sum()\n  |> aggregateWindow(every: 30m, fn: max, createEmpty: true)\n  |> derivative(unit: 1h)  \n// |> group()\n"
    }
   ]
  },
  { "title": "Comments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Comments",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "query": "from(bucket: \"views\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"views\")\n  |> filter(fn: (r) => r[\"_field\"] == \"comments\")\n  |> filter(fn: (r) => r[\"url\"] == \"${video_url}\")\n  |>drop(columns: [\"strategy_id\"])\n  |>group(columns: [\"url\"])\n// |> sum()\n  |> aggregateWindow(every: 30m, fn: max, createEmpty: true)"
    }
   ]
  },
  {
   "title": "Hourly Comments",
   "type": "barchart",
   "description": "Each bar is the difference previous hour to listed hour ",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "query": "from(bucket: \"views\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"views\")\n  |> filter(fn: (r) => r[\"_field\"] == \"comments\")\n  |> filter(fn: (r) => r[\"url\"] == \"${video_url}\")\n  |>drop(columns: [\"strategy_id\"])\n  |>group(columns: [\"url\"])\n// |> sum()\n  |> aggregateWindow(every: 30m, fn: max, createEmpty: true)\n  |> derivative(unit: 1h)  \n |> group()\n    |> keep(columns: [\"_time\", \"_value\"])\n"
    }
   ]
  }
 ]
}