{
 "title": "Sponsor Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "sponsor_id", "label": "Sponsor ID" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select name from sponsor where id = ${sponsor_id}"
    }
   ]
  },
  {
   "title": "Video Views",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "query": "from(bucket: \"views\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"views\")\n  |> filter(fn: (r) => r[\"_field\"] == \"views\")\n  |> filter(fn: (r) => r[\"sponsor_id\"] == \"${sponsor_id}\")\n  |>drop(columns: [\"strategy_id\"])\n  |>group(columns: [\"url\"])\n// |> sum()\n  |> aggregateWindow(every: 60m, fn: max, createEmpty: false)\n //  |> group()\n // |> aggregateWindow(every: 60m, fn: sum, createEmpty: false)\n  |> keep(columns: [\"_time\", \"url\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Video Views",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "query": "from(bucket: \"views\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"views\")\n  |> filter(fn: (r) => r[\"_field\"] == \"views\")\n  |> filter(fn: (r) => r[\"sponsor_id\"] == \"${sponsor_id}\")\n  |>drop(columns: [\"strategy_id\"])\n  |>group(columns: [\"url\"])\n// |> sum()\n  |> aggregateWindow(every: $__interval, fn: max, createEmpty: false)\n //  |> group()\n // |> aggregateWindow(every: $__interval, fn: sum, createEmpty: false)\n  |> keep(columns: [\"_time\", \"url\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Sales",
   "type": "timeseries",
   "description": "Shows you the correlation between video views and shopify sales",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$[*].Key", "type": "time" },
      { "jsonPath": "$[*].RevenueActual", "language": "jsonpath", "name": "With Videos", "type": "number" },
      { "jsonPath": "$[*].RevenuePredicted", "language": "jsonpath", "name": "Without Videos", "type": "number" }
     ],
     "method": "GET",
     "params": [
      [
       "start_date",
       "${__from}"
      ],
      [
       "end_date",
       "${__to}"
      ],
      [
       "interval",
       "${__interval_ms}"
      ],
      [
       "sponsor_id",
       "${sponsor_id}"
      ]
     ]
    }
   ]
  },
  {
   "title": "Hourly Video Views",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "query": "from(bucket: \"views\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"views\")\n  |> filter(fn: (r) => r[\"_field\"] == \"views\")\n  |> filter(fn: (r) => r[\"sponsor_id\"] == \"${sponsor_id}\")\n  |>drop(columns: [\"strategy_id\"])\n  |>group(columns: [\"url\"])\n// |> sum()\n  |> aggregateWindow(every: $__interval, fn: max, createEmpty: false)\n  |> derivative(unit: 1h, nonNegative: true)\n //  |> group()\n // |> aggregateWindow(every: $__interval, fn: sum, createEmpty: false)\n  |> keep(columns: [\"_time\", \"url\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Total views",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 5 }
   ]
  },
  {
   "title": "Your Videos",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT video.url, video.posted_date, statistics.views_total, video.sponsor_rate from statistics join video on statistics.video_id = video.id where video.sponsor_id = $sponsor_id ORDER BY video.posted_date desc"
    }
   ]
  },
  {
   "title": "Payments",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT date, amount, details FROM sponsor_payment WHERE sponsor_id = $sponsor_id "
    }
   ]
  }
 ]
}